apiVersion: v1
kind: Pod
metadata:
  labels:
    app: emailservice
spec:
  containers:
  - name: py-build
    image: 134448505602.dkr.ecr.ap-south-1.amazonaws.com/msdemo-emailservice-build:latest
    command:
      - cat
    tty:  true
    volumeMounts:
        - name: home-jenkins
          mountPath: /home/jenkins/
    resources:
      limits:
        memory: "2Gi"
        cpu: "1000m"
  - name: buildkit
    image: moby/buildkit:v0.15.0
    command:
      - cat
    tty: true
    volumeMounts:
        - name: home-jenkins
          mountPath: /home/jenkins/
        - name: buildkit-secret
          mountPath: /root/.docker
        - name: certs
          mountPath: /certs
  volumes:
    - name: home-jenkins
      emptyDir: {}
    - name: buildkit-secret
      secret:
        secretName: ecr-cred
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: certs
      secret:
        secretName: buildkit-client-certs
